version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: insure
    container_name: insure-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./insure/:/var/www
    networks:
      - insure

  nginx:
    image: nginx:alpine
    container_name: insure-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./insure/:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - insure

  MySQL:
    image: mysql:latest
    container_name: insure-MySQL
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: insure
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_PASSWORD: root
      # MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - insure

  phpMyAdmin:
    image: phpmyadmin:latest
    container_name: phpMyAdmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: MySQL
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - insure
    depends_on:
      - MySQL



networks:
  insure:
    driver: bridge